export const SET_USER_ROLE = 'SET_USER_ROLE';
export const LOGOUT = 'LOGOUT';

export const TOGGLE_JOB_STATUS = 'TOGGLE_JOB_STATUS';
export const TOGGLE_MARK_TALENT = 'TOGGLE_MARK_TALENT';
export const DELETE_TALENT = 'DELETE_TALENT';
export const DELETE_JOB = 'DELETE_JOB';
export const LOAD_POSTS = 'LOAD_POSTS';
export const POSTS_LOADING = 'POSTS_LOADING';
export const POST_BY_ID_LOADING = 'POST_BY_ID_LOADING';
export const LOAD_POST_BY_ID = 'LOAD_POST_BY_ID';